project:
  type: website

website:
  title: FAB
  favicon: /img/QUB_QBS_Logo_Red_Landscape.png
  twitter-card: true
  site-url: https://q-rap.connect.qub.ac.uk/FAB/
  body-footer: |
   ![](/img/QUB_QBS_Logo_Red_Landscape.png){width="50%"}
  open-graph:
    locale: es_ES
    site-name: FAB
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "People"
        menu:
          - people.qmd
      - text: "Activities"
        file: activity.qmd
      - text: "The Practical Intellectualist" 
        menu:
          - text: "About"
            file: pracademic.qmd
          - text: "Pracdemic Blog"
            file: blog.qmd
          - text: "AI and the Future of Education Series"
            file: eduAIseries.qmd
      - text: "Publications"
        file: pubs.qmd
format:
  html:
    theme: journal
    css: mycssblend.css
    toc: true

editor: visual