project:
  type: website
  render: 
    - about.qmd
    - activity.qmd
    - people.qmd
    - symposium.qmd
    - opportunities.qmd
    - pracademic.qmd
  
website:
  title: FAB
  body-footer: |
   ![](/img/QUB_QBS_Logo_Red_Landscape.png){width="50%"}
  open-graph:
    locale: es_ES
    site-name: FAB
  navbar:
    left:
      - about.qmd
      - activity.qmd
      - people.qmd
      - symposium.qmd
      - opportunities.qmd
      - pracademic.qmd
format:
  html:
    theme: journal
    css: mycssblend.css
    toc: true

editor: visual
