project:
  type: website
  
website:
  title: "**FAB**"
  body-footer: |
   ![](/img/QUB_QBS_Logo_Red_Landscape.png){width="50%"}
  open-graph:
    locale: es_ES
    site-name: FAB
  navbar:
    left:
      - about.qmd
      - activity.qmd
      - people.qmd
      - symposium.qmd
format:
  html:
    theme: journal
    css: mycss.css
    toc: true

editor: visual

