---
title: "About"
bibliography: refs.bib
css: mycss.css
---

At the Finance and AI Research Lab, Queen's Business School, we recognize the application of artificial intelligence in financial services as a <a class="glowinline">wicked problem:</a>,

> A problems with combined degrees of conflict [@Adelson2023], complexity [@Kelly2023] and uncertainty[@Dotan1985] [^1].

[^1]: Effective approaches for tackling <a class="glowinline">wicked problems</a> apply problem-solving paradigms that consider the complexity and interconnectedness of the problem and are effective when dealing with informational uncertainty.

<br>

## Our Mission

Our mission is to delve into this intricate nexus where innovative solutions meet multifarious challenges, a domain where simple answers are elusive, and the ramifications are profound and far-reaching. In this landscape, we are committed to pioneering AI solutions that not only advance financial practices but also address the inherent uncertainties and interdependencies characteristic of wicked problems in finance.

Our focus extends beyond the technical prowess of AI in predictive analytics and decision-making; we are equally invested in untangling the intertwined issues of ethical AI deployment, regulatory compliance, and social responsibility. We acknowledge that in the realm of AI and finance, the challenges we face are dynamic and evolving, demanding adaptive and forward-thinking strategies.

## Our Vision

The lab's vision encompasses not just the development of robust AI models but also the cultivation of frameworks that allow us to 'constrain our future selves', a concept central to addressing super wicked problems [@Levin2012OvercomingTS]. This involves proactive engagement with the long-term implications of our work, ensuring that our innovations in AI are sustainable, equitable, and transparent.

## Our Approach

Our interdisciplinary approach combines expertise in finance, technology, data science, and ethics, fostering an environment where creative problem-solving thrives. As we tackle these <a class="glowinline">wicked problems</a>, our lab stands as a crucible of innovation, shaping a future where AI in financial services is not just about efficiency and profit, but also about creating a more inclusive and responsible financial ecosystem.

In this challenging yet exhilarating journey, the Finance and AI Research Lab at Queen's Business School is dedicated to leading the charge, offering groundbreaking insights and solutions that resonate with the complex, interwoven fabric of modern financial services in an AI-driven era.
