---
title: "People"
---

-   Barry Quinn (Senior Lecturer of Finance, Technology and Data Science) **Director**

-   Fearghal Kearney (Senior Lecturer of Finance) **Director**

-   Gareth Campbell (Professor of Finance)

-   Declan French (Professor of Finance)

-   Declan Breslin (Honorary Professor of Practice in Financial Services)

-   Darren Burrows (CEO Funds-Axis Ltd)

-   Carla McGlynn (Director, Head of Markets Data, Business Risks and Controls Technology / Site Lead at Citi Belfast)

-   Dennis Krupen (SVP, Engineering Strategy, Data and DevOps Lead at Citi)

-   Clare Guinness (Innovation Director, Belfast Region City Deal)

-   Philip Hamill (Professor of Finance, Associate Provost for Research and Academic Department, Abu Dhabi University)

-   Paul Miller (Reader of Computer Science, Deputy Head of the Centre for Secure and Intelligence Technologies)

-   Hui Wang (Professor of Computer Science)

-   Jesus Martinez Del Rincon (Senior Lecturer of Computer Science)

-   Richard Gault (Lecturer in Computer Science)

-   Laura Steele (Senior Lecturer of Management)

-   Clive Walker (Lecturer of Finance)

-   Yassine Bakar (Lectuer of Finance)

-   Byron Graham (Senior Lecturer of Business Analytics)

-   Qiao (Olivia) Peng (Lecturer of Business Analytics)

-   Colm Kelly (Machine Learning Researcher, FundAxis Ltd; PhD completed 2023 in financial machine learning and asset pricing,)

-   Abhishek Pramanick (PhD Candidate in regulatory technology and financial inclusion, started Sept 22)

-   Fei Li (PhD Candidate in Firm risk and performance implications of ESG, started Sept 22)

-   Veronica Zhang (PhD Candidate in Regulatory Implications in the development of the Chinese banking sector (submitting July 2023)

-   Bart Ruemkens (PhD in climate finance, transition risk and the role of machine learning)

-   Weilong Lui (Market manipulation and the role of Supervisory Technology in the Chinese Stock Market)

We also have an institutional partnership with the [Gilmore Center for Financial Technology](https://www.wbs.ac.uk/research/research-centres-and-networks/gillmore-centre-financial-technology/) at Warwick Business School.
