---
title: "Rationale"
---

The financial services industry has witnessed a rapid expansion in the use digital innovation with early estimates suggesting an upper bound in annual value potential of one trillion dollars (or 13.4% of sales) globally[^1]. As a highly regulated system, the key drives of further technological adoption are:

[^1]: McKinsey AI Playbook (2019) estimates are anchor from 2016 financial data for the global banking sector. See <https://www.mckinsey.com/capabilities/quantumblack/our-insights/the-executives-ai-playbook?page=industries/banking/> for more details.

1.  operational resilience regulations;

2.  Cloud migration for business agility, economic **sustainability** , and net-zero environmental benefits;

3.  Cyber security, risk and privacy;

4.  AI and machine learning adoption.

The trends in digital finance were facilitated by the growth of hybrid cloud and advances in digital automation. All four drivers have strong links to research areas of AI-safety (in computer science) and risk management (in finance), and financial regulators across the world are grappling with "rules on the books" to provide robust guide rails for this viral-like growth of the digital economy.

# Why F.A.B. at Queen's University Belfast?

-   Northern Ireland is recognised as a world-leading cyber security ecosystem underpinned by QUB's CSIT (Centre for Secure Intelligent Technology) -- the UK's largest cybersecurity-focused university technology partner.

-   The ability to write bespoke training programmes and provide skills required (albeit lead time is required).

-   Existing core tech capability to be enhanced via Belfast Region City Deals and the overall 10X economic strategy in NI.

-   The unique location gives access to UK and EU markets.

Queen's Management School are uniquely positioned to establish an emerging research lab for financial technology, working in partnership with CSIT, to provide business and financial insights for the digital economy.
